Update README.md
ANF/Draft pull request #19
Opened 2021-01-04 23:04 UTC by mellobacon

Addressing #17.
Some preview images showing the different themes and the markdown renderer.

2021-01-05 11:01 UTC, ANF-Studios commented on README.md
> +<h4><strong>[RECOMMENDED]</strong> Using PowerShell</h4>
Ayy, thanks for pointing this out and fixing it.

2021-01-05 11:02 UTC, ANF-Studios commented on README.md
> +
Requires some indentation.

2021-01-05 11:27 UTC, ANF-Studios requested changes
You could work on what I specified in those comments.

2021-01-05 11:30 UTC, mellobacon commented
Alrighty then

2021-01-05 22:18 UTC, mellobacon commented
Formatted.

2021-01-07 13:05 UTC, ANF-Studios approved these changes
Alright, looks good enough to me.

2021-01-07 13:06 UTC, merged